services:
  app:
    build: .
    container_name: canaiguess-app
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8080:8080"
    networks:
      - canaiguess-net

networks:
  canaiguess-net:
