services:
  db:
    image: postgres:16
    container_name: canaiguess-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - canaiguess-net

  app:
    build: .
    container_name: canaiguess-app
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      CAPTCHA_SECRET_KEY: ${CAPTCHA_SECRET_KEY}
      cloudflare.r2.access-key: ${CLOUDFLARE_R2_ACCESS_KEY}
      cloudflare.r2.secret-key: ${CLOUDFLARE_R2_SECRET_KEY}
      cloudflare.r2.bucket-name: ${CLOUDFLARE_R2_BUCKET_NAME}
      cloudflare.r2.endpoint: ${CLOUDFLARE_R2_ENDPOINT}

    ports:
      - "8080:8080"
    networks:
      - canaiguess-net

  test:
    image: maven:3.9.6-eclipse-temurin-21
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - canaiguess-net
    command: mvn test
    profiles: [ "test" ]
    restart: "no"

networks:
  canaiguess-net:

volumes:
  postgres_data:
